---
#-------------------------------
# General Site Settings
title: Ali Raza
logo: # You can add own logo. For example '/images/logo.png'.
description: Super Dev, Software Architect, Coffee Extraiordinare
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aliirz.com" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Ali Raza
  bio: As a thorough software architect, I bring precision and passion to every software project I tackle. My goal is to always produce innovative and high-quality software that pushes the boundaries of what's possible. I have a love for experimenting with new programming languages, and you can catch me blogging about my experience and insights in the software development world. Join me in my journey as I explore the ever-evolving world of technology and programming.
  avatar: "/images/743962.jpeg"

social:
  - {
      icon: "ion-logo-twitter",
      label: Twitter,
      link: "https://twitter.com/aliirz",
    }
  - {
      icon: "ion-logo-github",
      label: Github,
      link: "https://github.com/aliirz",
    }
  - {
      icon: "ion-logo-facebook",
      label: Facebook,
      link: "https://facebook.com/aliirz",
    }
  - {
      icon: "ion-logo-youtube",
      label: Youtube,
      link: "https://www.youtube.com/channel/UCc5gunCRatvlC1CD_3an1tw",
    }
  - {
      icon: "ion-logo-twitch",
      label: Twitch,
      link: "https://twitch.com/aliirz",
    }
  # - { icon: "ion-logo-dribbble", label: Dribbble, link: "https://dribbble.com" }
  - {
      icon: "ion-logo-instagram",
      label: Instagram,
      link: "https://instagram.com/aliirz",
    }
  # - { icon: "ion ion-logo-vimeo", label: Vimeo, link: "https://vimeo.com" }

# Example of adding a new link to the author section and footer - {icon: "ion-logo-github", label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: Hey, I am Ali! Builder of stuff.
  hero__description: As a detail-oriented software architect, I bring precision and passion to every project I tackle. From building cutting-edge software to exploring the latest trends in civic tech, gaming, and 3D printing, I am always pushing the boundaries of what's possible. In my free time, I enjoy sharing my insights and experiences through my blog, giving readers a glimpse into the exciting world of tech and innovation. Let's build something cool together!
  hero__image: "/images/743962.jpeg"

#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp: false # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp__title: Get interesting news # Add your Title
mailchimp__text: Subscribe to our newsletter and we will send you the emails of latest posts. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Join # Add your button text

#-------------------------------
# Contact Settings
contact:
  email: dejavu87@gmail.com # Add your email for contact form
  description: Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: aliirz # add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google-analytics: G-X5MSM54ZQZ # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title

sass:
  sass_dir: _sass
  style: compressed

twitter:
  username: aliirz
  card: summary